### ISSUE TITLE
Coursera submission times out frequently

### ISSUE THREAD

**Issue by dniku** [yandexdataschool/Practical_RL#125]
See e.g.

* Week 1
  * https://www.coursera.org/learn/practical-rl/discussions/all/threads/shgOWhD6Eem05w6AgdnUUg
  * https://www.coursera.org/learn/practical-rl/discussions/all/threads/f0n8VjHZEem1TQp52mPyzA
  * https://www.coursera.org/learn/practical-rl/discussions/all/threads/4-zMLDR3EemQog4QqCq2DA
* Week 2
  * https://www.coursera.org/learn/practical-rl/discussions/all/threads/1yBwzC_JEemFtBIW2Sb6Og
  * https://www.coursera.org/learn/practical-rl/discussions/all/threads/bgJFTRHrEem5lg4iKF5GLg
  * https://www.coursera.org/learn/practical-rl/discussions/all/threads/LgMOpTNgEem3MQ5UkLSNGA
  * https://www.coursera.org/learn/practical-rl/discussions/all/threads/FEPk6IxAEem0yBI86_RF3A
* Week 6
  * https://www.coursera.org/learn/practical-rl/discussions/all/threads/E9X7HTP3Eem8yQpzN9iFFg

The problem seems intermittent (I haven't been able to reproduce it, but many students on Coursera reported it).

The problem is most likely outside of our control, so this issue exists mostly for gathering reports and communicating with Coursera support.

**Comment by Pastafarianist** [comment]
Coursera support say that a fix has been deployed. I will reopen the issue if this arises again.

**Comment by Anil1331** [comment]
Still facing the issue, stuck at submit phase and getting dead within few minutes

**Comment by Pastafarianist** [comment]
Forwarded @Anil1331's complaint to Coursera support.

**Comment by Pastafarianist** [comment]
Closing as there have not been any reports recently.

**Comment by Pastafarianist** [comment]
New report at https://www.coursera.org/learn/practical-rl/discussions/all/threads/FEPk6IxAEem0yBI86_RF3A .

**Comment by dniku** [comment]
No reports of this for a while.

**Comment by MehaRima** [comment]
Tried multiple times but still getting this error using the updated notebook !
Please help

![problem-2020 08 13-00_46_20946](https://user-images.githubusercontent.com/26185528/90058578-89822380-dcff-11ea-8e42-e6f93ec2822b.png)

**Comment by dniku** [comment]
@MehaRima your problem is unrelated to the topic of this issue. I would guess that most likely you passed a Numpy array instead of a number as `t_max`. If you need more help, please create a new issue or post in the Coursera forum.

**Comment by MehaRima** [comment]
> @MehaRima your problem is unrelated to the topic of this issue. I would guess that most likely you passed a Numpy array instead of a number as `t_max`. If you need more help, please create a new issue or post in the Coursera forum.

Thank you for your response.
I have created a new issue 
in the course forum already.
